### ISSUE TITLE
rustup uses stable at first deploy, ignoring RustConfig's $VERSION

### ISSUE THREAD

**Issue by tjikini** [emk/heroku-buildpack-rust#16]
https://github.com/emk/heroku-buildpack-rust/blob/master/bin/compile#L86-L93

**Comment by emk** [comment]
Good catch! Thank you for finding this. Now lets see if I can remember the necessary rustup flags to fix it.

**Comment by elifoster** [comment]
--revision=$VERSION is how you specify a version.

**Comment by tjikini** [comment]
_--default-toolchain_, i guess.

@elifoster _--revision_ is for [rustup.sh](rust-lang/rustup.sh), not for [rustup.rs](rust-lang-nursery/rustup.rs).

**Comment by emk** [comment]
ack. Will look at this later.

**Comment by elifoster** [comment]
@tjikini rustup.sh is what is used by this buildpack, not rustup.rs.

**Comment by emk** [comment]
No, I switched it during the last round of updates I did, because it could
self upgrade.

**Comment by elifoster** [comment]
Yeah I just noticed that. It gets named as rustup.sh which is what confused me.

**Comment by emk** [comment]
OK, just a reminder to myself that I want to fix this soon.
