### ISSUE TITLE
Not detecting nightly?

### ISSUE THREAD

**Issue by steveklabnik** [emk/heroku-buildpack-rust#20]
I have a project that needs nightly (or beta)...

I have a `Rustconfig` file with this in it:

    VERSION=nightly

yet the buildpack still tries to use stable. Am I doing something wrong? I was looking at the code, i dunno.

**Comment by steveklabnik** [comment]
Sorry, it was `Rustconfig` not `RustConfig`! Fixed.

**Comment by emk** [comment]
No problem! I dream of the day when there's a metadata convention for
storing this information in Cargo.toml. :-)

Le 12 janv. 2017 4:55 PM, "Steve Klabnik" <notifications@github.com> a
écrit :
