### ISSUE TITLE
VERSION=1.X not supported anymore

### ISSUE THREAD

**Issue by palfrey** [emk/heroku-buildpack-rust#26]
Despite what the README says, setting e.g "VERSION=1.20" doesn't work. You get

```-----> Rust app detected
-----> Downloading rustup
-----> Using rustup to install Rust channel 1.20
info: downloading installer
error: invalid toolchain name: '1.20'
 !     Push rejected, failed to compile Rust app.
 !     Push failed```

**Comment by emk** [comment]
You need to set `VERSION=1.20.0`, which is the actual version number supported by `rustup`. I've updated the README to make this clearer. Thank you!
