### ISSUE TITLE
 Cannot find lsqlite3

### ISSUE THREAD

**Issue by NAlexPear** [emk/heroku-buildpack-rust#43]
When building an `actix_web`-based application with this buildpack, we've recently been running into a compile-time issue related to `lsqlite3`. Here's the abbreviated output of the error we're getting:

```
error: linking with `cc` failed: exit code: 1

 // snip

  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L"
  = note: /usr/bin/ld: cannot find -lsqlite3

          collect2: error: ld returned 1 exit status
```

We are not seeing any similar linking issues when building from the latest `rust` docker containers using `heroku.yml`, so this might have something to do with the `heroku-18` stack.

**Comment by emk** [comment]
I'm sorry to hear that.

There should be a working actix example linked from the README. Do you know whether that still works?

**Comment by JakubKoralewski** [comment]
I'm running into the same problem. The reason why this happens (I presume) is that locally I installed diesel_cli using this command:
```
cargo install diesel_cli --no-default-features --features postgres
```
It would be nice to be able to specify this somehow.

Should I specify the DIESEL_FLAGS environment variable? If so, it would be nice to be documented.

https://github.com/emk/heroku-buildpack-rust/blob/cfa0f0621411f0dbb46df9d4740e119b7a459ccc/bin/compile#L150

It does not solve the problem.
 
I solved it by adding another buildpack that installs a package you can specify in an Aptfile. Here's [the fixing commit](https://github.com/JakubKoralewski/dziennik-rust/commit/86d807e8e8a4748a708d8700dee6a2f263c37c07) in my repo.

**Comment by emk** [comment]
I believe you should be able to fix this by specifying the following in `RustConfig`:

```sh
DIESEL_FLAGS="--force --no-default-features --features postgres"
```

If you try this, please let me know whether it works. :-) If somebody can confirm this for me, I'll update the buildpack accordingly ASAP. Thank you very much!

**Comment by JakubKoralewski** [comment]
To be honest, I got it working beforehand. I added it just to be sure lol, but can't tell if that was it. I set it in the environment as well, because I thought in the code you reference env variables but it seems it's the RustConfig file?

**Comment by NAlexPear** [comment]
Thanks for the quick reply @emk!

We're using [`dbmigrate-lib`](https://github.com/Keats/dbmigrate) for in-app migrations instead of `diesel`, but the advice of restricting features to `postgres` turned out to be the correct approach. It looks like the `libsqlite3-dev` package that @JakubKoralewski was installing through `apt` is, as expected, [not supported in Heroku's stacks](https://devcenter.heroku.com/articles/stack-packages).

So this turned out not to be a buildpack-specific issue in our case, but worth mentioning for future searchers that SQLite support (even as an inadvertent build dependency) is spotty at best on Heroku, and should probably be explicitly disabled.
