### ISSUE TITLE
Cannot get nightly to build

### ISSUE THREAD

**Issue by Standaa** [emk/heroku-buildpack-rust#49]
Hello,
I have looked at other issues, but none of the solutions worked.

I am trying to get the nightly to build on Heroku, because of Rocket.rs.
I have specified a RustConfig file, a  rust-toolchain file, a RUSTUP_TOOLCHAIN env var both on Heroku and my machine. Nothing worked so far.
I also set rustup to default to the nightly on my machine.
I can see the build is always picking up stable. Nonetheless, nothing in my app seems to specify it.

The example works fine though. Any pointers ?
Thanks!

**Comment by Standaa** [comment]
Ahem, really stupid mistake: Made a branch heroku-config, but was pushing my local master.
All good, closing.

**Comment by istx25** [comment]
Hi @stanislasdrg,

Can you share more about how you fixed this? Like the config file you had please? Thanks!
