### ISSUE TITLE
Allow developer to specify a channel instead of a specific rust version

### ISSUE THREAD

**Issue by frewsxcv** [emk/heroku-buildpack-rust#5]
It'd be helpful to have a way to specify CHANNEL="nightly", CHANNEL="beta", or CHANNEL="stable" instead of locking onto a specific version

**Comment by emk** [comment]
This is an interesting idea.

Personally, my bias is to always deploy applications with a specific, known language version, and to record that version as part of the project. The idea is that I might want to come back to a deployed project 9 months later and make a small fix, without updating to the latest versions of everything.

On the other hand, Rust seems to take stability pretty seriously, so maybe it would be feasible to use something like "Rust >= 1.0.0 and < 2.0.0".

I'll implement this if lots of people want it, or if somebody makes a really convincing argument for it. But my personal bias is towards specifying an exact, known-good version when deploying.

**Comment by emk** [comment]
This should now be implemented via Rustup, thanks to #8 and recent changes to `master`.
