### ISSUE TITLE
Timeout on Build

### ISSUE THREAD

**Issue by KindaSloth** [emk/heroku-buildpack-rust#56]
Hi guys, I'm trying to deploy an api made with actix and I'm having problems with timeout during build, does anyone know how I can increase this timeout or how to solve my problem ? print of the log: https://twitter.com/KindSloth/status/1408551910123126785/photo/1

**Comment by RogueMacro** [comment]
Did you find a solution? I'm also having this problem just with rocket, where it will get stuck at `Compiling rocket_codegen`

**Comment by KindaSloth** [comment]
I ended up not finding a solution, so I used docker for deploy my application

**Comment by emk** [comment]
Docker is, indeed, an excellent choice for anything complicated.
