### ISSUE TITLE
Ruby application with Rust dependencies

### ISSUE THREAD

**Issue by elifoster** [emk/heroku-buildpack-rust#9]
I've got a gem, string-utility, which is written in Rust using ruru for a few of its methods. I am trying to use this buildpack to install Rust and Cargo (without running `cargo build`, I can just fork the project and remove that tiny amount of code since it's a pretty uncommon desire at this point I'd imagine). However, it seems, even if the Rust buildpack runs successfully, Bundler is unable to find `cargo` or `rustc` to compile string-utility's Rust code. There was a similar question #6, except that question was regarding a project that was written with Node and Rust, not Node with Rust dependencies. In other words, it actually wanted to compile Rust code, then run Node separately. I've been trying to figure this out through experimentation and talking with Heroku support, and I've been unsuccessful for about 3 weeks. The majority of my projects depend on this library, and chances are, once I figure this out, many of my other libraries are going to be rewritten partially in Rust.

I'm not really sure how to briefly ask what I'm trying to ask here. I suppose:
* Is using this buildpack the correct way to get Rust/Cargo installed on a Heroku project?
* If so, how can I get it to install such that Bundler can actually find it, or is that a bug in the buildpack?

My buildpack order: 1. emk/heroku-buildpack-rust, 2. heroku/ruby

**Comment by schneems** [comment]
To clarify this issue, the Rust buildpack needs to export the PATH and any other environment variables that it needs for other buildpacks to be able to find the rust or cargo executables.

The multi buildpack supports a directory you can write to that will be sourced into the environment after every buildpack is run. 

You can see how this is done in the official Ruby buildpack here: https://github.com/heroku/heroku-buildpack-ruby/blob/088683acf9f6edde85179061480ec1850956cc2f/lib/language_pack/ruby.rb#L290-L306

That's all you have to do. Once you write the environment variables to that dir then the next buildpack will be able to find the executables. Let me know if you have any questions. I maintain the Ruby buildpack.

**Comment by emk** [comment]
Ah, thank you! I need to look at this buildpack this week-end and merge
some patches.
Le 10 juin 2016 10:01 AM, "Richard Schneeman" <notifications@github.com> a
écrit :

**Comment by elifoster** [comment]
@schneems What is "that dir"? I took a look in the logs of the ruby buildpack, and it looks like the ruby executable is at `build_path/vendor/ruby-2.3.0/bin/ruby`, so I tried putting rust and cargo in `build_path/vendor` and exporting PATH, but it doesn't seem to have made any difference.

PATH at the end of the Rust buildpack's compile script (build path shortened to build_path for sanity): `build_path/vendor/rust-cache-1.8.0/rust-1.8.0-x86_64-unknown-linux-gnu/rustc/bin:build_path/vendor/rust-cache-1.8.0/rust-1.8.0-x86_64-unknown-linux-gnu/cargo/bin:/app/bin:/app/vendor/bundle/bin:/app/vendor/bundle/ruby/2.3.0/bin:/usr/local/bin:/usr/bin:/bin:/tmp/codon/vendor/bin`

`cargo --version` and `rustc --version` have the expected results. Yet Ruby/Bundler still cannot find cargo or rustc.

[My fork](https://github.com/elifoster/heroku-buildpack-rust).

**Comment by schneems** [comment]
Sorry for delay. Here's the code that does it

https://github.com/heroku/heroku-buildpack-multi/blob/26fa21ac7156e63d3d36df1627329aa57f8f137c/bin/compile#L55-L57

It looks like you actually write it to the same directory the buildpack is in.

The ruby buildpack figures out what directory that is here https://github.com/heroku/heroku-buildpack-ruby/blob/088683acf9f6edde85179061480ec1850956cc2f/lib/language_pack/base.rb#L20 and then here's our "add to export" method https://github.com/heroku/heroku-buildpack-ruby/blob/088683acf9f6edde85179061480ec1850956cc2f/lib/language_pack/base.rb#L164-L169.

**Comment by emk** [comment]
After looking at this bug report, I'm not sure I understand all the issues involved. If somebody would like to prepare a pull request so that I can visualize what needs to happen, I'd definitely be interested.

**Comment by schneems** [comment]
My bash is pretty rusty. Here's the gist of what you need to do, but it my not be perfect:

```
# Find directory of `bin` where `bin/compile` is located
bin_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Find directory that buildpack is in, up one level from `bin`
# then create an `export` file
export_file="$bin_dir/../export"
touch $export_file

# Now here is where you would add anything to the environment that is needed for Rust to run

# Set CARGO_HOME for next buildpack
echo "export CARGO_HOME="$CARGO_HOME"" >> $export_file

# Set CARGO_TARGET_DIR for next buildpack
echo "export CARGO_TARGET_DIR="$CARGO_TARGET_DIR"" >> $export_file

# Prepend PATH so this Rust is guaranteed to come first
echo "export PATH="$PATH:\$PATH"" >> $export_file
```

Then when multiple buildpacks this `export` file will be sourced and then the next buildpack can find all those environment variables, as well as see that Rust is on the path.

**Comment by emk** [comment]
@schneems OK, I have a branch which should implement this, assuming I understood the spec correctly.

I don't export `CARGO_TARGET_DIR`; you should be able to find that as `./target` in your source directory. Please let me know if this works. If it does, I'll go ahead and merge it.
